
fields:
  Matter.Client.Name:
    - "Patient Name"
    - "Client Name"
    - "Name"

  Matter.CustomField.DateOfLoss:
    - "Date of Incident"
    - "Date of Loss"
    - "Accident Date"
  Insurance.AdjusterName.FullName:
    - "Adjuster Name:"
    - "Claims Adjuster:"

  Matter.CustomField.ClaimNumber:
    - "Claim Number:"
    - "Claim No:"
    - "Ref No:"
  Contact.Client.Phone:
    - "Business Phone"
    - "Phone Number"
  Matter.Client.Address:
    - "Home Address:"
    - "Work Address:"
    - "Busines Address:"
  Matter.Client.HourlyWage:
    - "Regular Pay:"
    - "Hourly Rate:"
  Matter.Client.HoursWorked:
    - "Total Hours Worked"
    - "Hours Worked"
  Firm.Attorney:
    - "Attorney:"
    - "Signed by:"
  Matter.OriginatingAttorney:
    - "Attorney:"
    - "Signed by:"
  User.Initials:
    = "Initials:"